name: "${APP_NAME}-test"
services:
  db_test:
    image: postgres:15
    container_name: db-test
    env_file: .env.test
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["-c", "max_connections=9999"]
    networks:
      - test-network

  redis_test:
    image: redis:6.2.6
    container_name: ${APP_NAME}-redis-test
    env_file: .env.test
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - "redis_test:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

volumes:
  postgres_data_test:
    driver: local
  redis_test:
    driver: local

networks:
  test-network:
    driver: bridge
