// This file is auto-generated by @hey-api/openapi-ts

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type GetApiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};