/**
 * GrowthBook Features TypeScript Typings
 *
 * NOTE: This file is auto generated by the GrowthBook CLI (https://docs.growthbook.io/tools/cli).
 * See https://docs.growthbook.io/tools/cli#generating-types for more information.
 *
 * DO NOT EDIT this file manually.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type -- this won't be empty in an actual app with feature flags defined here
export type AppFeatures = {};
