name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint-typecheck-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12"

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.3

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Setup test environment
        run: docker compose -f docker-compose.test.yml up -d

      - name: Test
        run: pnpm test

      - name: Tear down test environment
        run: docker compose -f docker-compose.test.yml down
        if: always() # This ensures the tear down happens even if previous steps fail
