name: UI Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "spa/**"
      - ".github/workflows/spa.yaml"

jobs:
  lint-typecheck-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./spa"
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.3

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint
